#!/usr/bin/env perl
# /=====================================================================\ #
# |  maketest                                                           | #
# | Tool to generate an integration test                                | #
# |=====================================================================| #
# | Part of BibTeXML                                                    | #
# |---------------------------------------------------------------------| #
# | Tom Wiesing <tom.wiesing@gmail.com>                                 | #
# \=====================================================================/ #

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use BiBTeXML::Cmd::maketest;
my $exitcode = BiBTeXML::Cmd::maketest->main(@ARGV);
exit $exitcode;

1;