#!/usr/bin/env perl
# /=====================================================================\ #
# |  runtest                                                            | #
# | Tool to run an integration test                                     | #
# |=====================================================================| #
# | Part of BibTeXML                                                    | #
# |---------------------------------------------------------------------| #
# | Tom Wiesing <tom.wiesing@gmail.com>                                 | #
# \=====================================================================/ #

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use BiBTeXML::Cmd::runtest;
my $exitcode = BiBTeXML::Cmd::runtest->main(@ARGV);
exit $exitcode;

1;
